hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_deepcfd/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval/export/inference
seed: 2023
output_dir: ${hydra:run.dir}
log_freq: 20

# set data file path
DATAX_PATH: ./datasets/dataX.pkl
DATAY_PATH: ./datasets/dataY.pkl
SLIPT_RATIO: 0.7 # slipt dataset to train dataset and test datatset
SAMPLE_SIZE: 981 # the shape of dataX and dataY is [SAMPLE_SIZE, CHANNEL_SIZE, X_SIZE, Y_SIZE]
CHANNEL_SIZE: 3
X_SIZE: 172
Y_SIZE: 79

# model settings
MODEL:
  input_key: "input"
  output_key: "output"
  in_channel: 3
  out_channel: 3
  kernel_size: 5
  filters: [8, 16, 32, 32]
  weight_norm: false
  batch_norm: false

# training settings
TRAIN:
  epochs: 1000
  learning_rate: 0.001
  weight_decay: 0.005
  eval_during_train: true
  eval_freq: 50
  batch_size: 64
  pretrained_model_path: null
  checkpoint_path: null

EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
  batch_size: 8

INFER:
  # 预训练模型的路径，加载预训练的模型参数
  pretrained_model_path: "https://paddle-org.bj.bcebos.com/paddlescience/models/deepcfd/deepcfd_pretrained.pdparams"

  # 导出的模型路径，用于保存推理所需的 .pdmodel 和 .pdparams 文件
  export_path: ./inference/deepcfd

  # 导出的模型文件路径，拼接后的文件路径包含 .pdmodel 和 .pdparams 文件
  pdmodel_path: ${INFER.export_path}.pdmodel
  pdiparams_path: ${INFER.export_path}.pdiparams

  # 推理使用的设备，这里指定为 GPU
  device: gpu

  # 使用的推理引擎，这里选择原生引擎
  engine: native

  # 推理的精度类型，fp32 为单精度浮点数
  precision: fp32

  # ONNX 导出的路径
  onnx_path: ${INFER.export_path}.onnx

  # 是否启用子图优化
  ir_optim: true

  # 子图优化的最小节点数
  min_subgraph_size: 10

  # 指定 GPU 可用内存大小，单位为 MB，这里设置为 6000 MB
  gpu_mem: 6000

  # 指定使用的 GPU ID
  gpu_id: 0

  # 批量推理时的最大批次大小
  max_batch_size: 100

  # 使用的 CPU 线程数
  num_cpu_threads: 4

  # 推理时输入数据的总大小，deepcfd 案例数据集的样本数为 981
  total_size: 981

  # 推理时每批次的数据大小，设置为 100，适用于 deepcfd 案例的批次处理
  batch_size: 100
